spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/to_do_list
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    # show-sql: true
    properties:
      hibernate.format_sql: true
  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true

